title: mkDlufop`s blog 
author: mkDlufop
subtitle: The life of a frustrated engineer

url: "https://mkdlufop.github.io"
#baseurl: ""

# footer_only_homepage: true
# footer_url: "https://github.com/pro-panda"
# footer_text: "Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Links"
   absolute-link: "https://mkdlufop.github.io/"

google:
    analytics_id: G-Q1QJCB6SJM
